-- AlterTable
ALTER TABLE "Lead" ALTER COLUMN "emailAddress" DROP NOT NULL,
ALTER COLUMN "bedrooms" DROP NOT NULL,
ALTER COLUMN "bathrooms" DROP NOT NULL,
ALTER COLUMN "bathrooms" SET DATA TYPE DOUBLE PRECISION;
